# Generated by Django 3.2.9 on 2021-12-11 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitud', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadSoli',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la Actividad')),
                ('id_act_soli', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('full_fecha_actividad', models.DateTimeField(auto_now=True, verbose_name='Fecha y Hora de la Actividad')),
                ('estado_act', models.SmallIntegerField(default=0, verbose_name='Estado')),
                ('sub_estado', models.BooleanField(default=False, verbose_name='Sub Estado')),
                ('profesional', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='solicitud.solicitud')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['created', 'estado_act'],
            },
        ),
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre de la Asesoria')),
                ('descripcion_inicio', models.TextField(max_length=150, verbose_name='Contenido')),
                ('estado', models.SmallIntegerField(default=0, verbose_name='Estado')),
                ('descrip_cierre', models.TextField(blank=True, max_length=150, verbose_name='Informacion Ciere')),
                ('sub_estado', models.BooleanField(default=False, verbose_name='Sub Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='actividad.actividadsoli')),
            ],
            options={
                'verbose_name': 'Asesoria',
                'verbose_name_plural': 'Asesorias',
                'ordering': ['actividad', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Tipoactividad',
            fields=[
                ('id_act', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_act', models.CharField(max_length=100, null=True, verbose_name='Tipo Empresa')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Tipo de actividad',
                'verbose_name_plural': 'Tipo de actividades',
                'ordering': ['order', 'nombre_act'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip_inicio', models.TextField(max_length=150, verbose_name='Contenido')),
                ('estado', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre de la Visita')),
                ('descrip_cierre', models.TextField(blank=True, max_length=150, verbose_name='Informacion Ciere')),
                ('sub_estado', models.BooleanField(default=False, verbose_name='Sub Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='actividad.actividadsoli')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['created', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FiscalizacionAsesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fiscalizador', models.CharField(max_length=100, verbose_name='Nombre del Fiscalizador')),
                ('email_fiscalizador', models.EmailField(blank=True, max_length=254)),
                ('estado', models.SmallIntegerField(default=0, verbose_name='Estado')),
                ('descrip', models.TextField(max_length=150, verbose_name='Contenido')),
                ('sub_estado', models.BooleanField(default=False, verbose_name='Sub Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('aseso', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='actividad.asesoria')),
            ],
            options={
                'verbose_name': 'Fiscalizacion',
                'verbose_name_plural': 'Fiscalizaciones',
                'ordering': ['aseso', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_inicio', models.TextField(max_length=150, verbose_name='Contenido')),
                ('estado', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre de la Capacitacion')),
                ('materiales', models.TextField(max_length=100, null=True, verbose_name='Materiales')),
                ('costo', models.CharField(max_length=7, verbose_name='Costo de Materiales')),
                ('nro_asistentes', models.IntegerField(verbose_name='Numero de Asistentes')),
                ('descrip_cierre', models.TextField(blank=True, max_length=150, verbose_name='Informacion Ciere')),
                ('sub_estado', models.BooleanField(default=False, verbose_name='Sub Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='actividad.actividadsoli')),
            ],
            options={
                'verbose_name': 'Capacitacion',
                'verbose_name_plural': 'Capacitaciones',
                'ordering': ['created', 'name'],
            },
        ),
        migrations.AddField(
            model_name='actividadsoli',
            name='tipo_act',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='actividad.tipoactividad', verbose_name='Actividad'),
        ),
        migrations.CreateModel(
            name='AccidenteAsesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causa', models.TextField(max_length=150, verbose_name='Causa')),
                ('estado', models.SmallIntegerField(default=0, verbose_name='Estado')),
                ('descrip', models.TextField(max_length=150, verbose_name='Contenido')),
                ('sub_estado', models.BooleanField(default=False, verbose_name='Sub Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('aseso', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='actividad.asesoria')),
            ],
            options={
                'verbose_name': 'Accidente',
                'verbose_name_plural': 'Accidentes',
                'ordering': ['aseso', 'created'],
            },
        ),
    ]
