# Generated by Django 3.2.9 on 2021-11-06 05:02

from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_tipoempresa_nombre_emp'),
        ('registration', '0002_auto_20211103_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.tipoempresa'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=registration.models.custom_upload_to, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Red Social'),
        ),
    ]
