# Generated by Django 3.2.9 on 2021-11-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20211106_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nivel_profile',
            field=models.SmallIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
