# Generated by Django 3.2.9 on 2021-11-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_profile_nivel_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='nivel_profile',
            field=models.SmallIntegerField(default=0, verbose_name='Nivel '),
        ),
    ]
