# Generated by Django 3.2.9 on 2021-12-01 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prevencionista', '0002_alter_prevencionista_run'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prevencionista',
            options={'ordering': ['user__username'], 'verbose_name': 'Prevencionista', 'verbose_name_plural': 'Prevencionistas'},
        ),
    ]
