# Generated by Django 3.2.9 on 2021-11-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_tipoempresa_nombre_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoempresa',
            name='nombre_emp',
            field=models.CharField(max_length=100, null=True, verbose_name='Tipo Empresa'),
        ),
    ]
