# Generated by Django 3.2.9 on 2021-12-01 17:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        ('empresa', '0003_alter_tipoempresa_nombre_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_emp', models.IntegerField(max_length=15, verbose_name='Rut Empresa')),
                ('nombre_emp', models.CharField(max_length=100, null=True, verbose_name='Nombre Empresa')),
                ('direccion_emp', models.CharField(max_length=100, verbose_name='Direccion Empresa')),
                ('fono_emp', models.IntegerField(verbose_name='Telefono')),
                ('email_emp', models.EmailField(blank=True, max_length=254, verbose_name='Correo electronico')),
                ('estado_emp', models.BooleanField(verbose_name='Estado Empresa')),
                ('razon_social_emp', models.CharField(max_length=100, verbose_name='Razon social')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['order', 'nombre_emp'],
            },
        ),
        migrations.CreateModel(
            name='TipoRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rubro', models.CharField(max_length=100, null=True, verbose_name='Nombre Rubro')),
                ('descripcion', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Tipo de Rubro',
                'verbose_name_plural': 'Tipo de Rubros',
                'ordering': ['order', 'name_rubro'],
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellido_pat', models.CharField(max_length=200, verbose_name='Apellido Paterno')),
                ('apellido_mat', models.CharField(max_length=200, verbose_name='Apellido Materno')),
                ('run', models.IntegerField(max_length=15, verbose_name='Run Trabajador')),
                ('orden', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('empresa', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'ordering': ['orden', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre Empresa')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('tipo_rubro', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='empresa.tiporubro')),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
                'ordering': ['order', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('estado', models.BooleanField(verbose_name='Estado Empresa')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('fecha_inicio', models.DateField(blank=True, verbose_name='Fecha de Inicio')),
                ('fecha_termino', models.DateField(blank=True, verbose_name='Fecha de Termino')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='empresa.empresa')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='manager.manager')),
                ('rubro', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='empresa.rubro')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['order', 'name'],
            },
        ),
    ]
