# Generated by Django 3.2.9 on 2021-12-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_contrato_empresa_rubro_tiporubro_trabajador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiporubro',
            name='descripcion',
            field=models.CharField(max_length=150, verbose_name='Descripcion'),
        ),
    ]
