# Generated by Django 3.2.9 on 2021-12-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_alter_tiporubro_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='rut_emp',
            field=models.CharField(max_length=15, verbose_name='Rut Empresa'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='nombre',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre del Rubro'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='run',
            field=models.CharField(max_length=15, verbose_name='Run Trabajador'),
        ),
    ]
