# Generated by Django 3.2.9 on 2021-12-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_auto_20211201_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='rut_emp',
            field=models.CharField(max_length=15, verbose_name='Rut (sin puntos con guion)'),
        ),
    ]
