# Generated by Django 3.2.9 on 2021-12-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0008_alter_empresa_rut_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='direccion_emp',
            field=models.TextField(max_length=100, verbose_name='Direccion Empresa'),
        ),
        migrations.AlterField(
            model_name='tiporubro',
            name='descripcion',
            field=models.TextField(max_length=150, verbose_name='Descripcion'),
        ),
    ]
